### PR TITLE
Added further checks in UWP

### PR DESCRIPTION
**Pull request by atymes**

### CODE REVIEW

**Comment by tjoneslo** [comment]
My one comment here is several versions of Traveller have Hydographyic = Flux + Size (not Atmosphere), and this system was used for generating many of the systems in the existing T5SS data sets. Implementing this will cause these worlds to generate errors on lint. And we should have a way to adjust the world.

**Comment by wvan478** [comment]
Perhaps there could be some kind of flag that marks a sector as having used Book-3 or Book-6 rules, so that the checker then uses the appropriate formula?

**Comment by inexorabletash** [comment]
I'll try patching this in locally and see how bad it is for existing sectors. My windows dev virtual machine is being a pain at the moment, though.

**Comment by inexorabletash** [comment]
Sorry I never took action on this. :( I totally forgot about it.

**Comment by atymes** [comment]
I thought you closed the pull request?

In any case, I wiped my fork because I need to commit the new Datsatl data,
and I figured that would be best done off a fresh fork.  Mongoose is
publishing JTAS 6, in which there will be mention of this sector, sooner
than expected.  Datsatl's ready for review; I had been waiting to finish
Gakghang before submission, but I no longer have that luxury.  I'll submit
Datsatl's pull request soon.

**Pull request closed without merging**
