### PR TITLE
Reduce stellar brightness over Hiver known-space

### PR DESCRIPTION
**Pull request by mmarquee**
Reduce stellar brightness (manually) to make these areas match more standard areas of space.

### CODE REVIEW

**Comment by mmarquee** [comment]
I am currently fixing the above conflicts

**Comment by mmarquee** [comment]
I have sorted out the merge conflicts.

Overall I have reduced the number of huge, bright stars. Doing a visual comparison, perhaps the Imperium area has more 'red' stars than these areas still.

**Comment by inexorabletash** [comment]
Looks great, thanks!

How did you do this? All manual, or with tooling?

**Comment by mmarquee** [comment]
I did it manually. Shifted most of the values for II -> IV and III -> V, but kept some and changed others, to make areas of 'interest'.
What was kept was pretty much on a whim.

**Pull request merged**
