### PR TITLE
Deneb fixins

### PR DESCRIPTION
**Pull request by bobbyjim**
I ran Deneb 1120 through your linter, and fixed line items.

Then I removed M1201/1201_Dene.sec in favor of M1201/Dene.tab.  You're right -- the .tab files are easier and less ambiguous to parse.

### CODE REVIEW

**Comment by inexorabletash** [comment]
Can you remove the .DS_Store files and re-push?

**Comment by bobbyjim** [comment]
Better?

**Comment by philoserf** [comment]
@bobbyjim Doesn’t the change to ignore belong, rather, in your global gitignore?

**Comment by bobbyjim** [comment]
Honestly don’t know, but I bet you’re right.

**Comment by philoserf** [comment]
Here is a good start. 

https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files

**Comment by bobbyjim** [comment]
Thanks.  So how does the PR look then?

**Comment by philoserf** [comment]
for that i defer to @inexorabletash and co.

**Review by inexorabletash — CHANGES_REQUESTED** [review]
Do a `git rm res/Sectors/.DS_Store` to pull that out of the change set.

Otherwise, change looks okay.

**Comment by bobbyjim** [comment]
It's gone.  Promise.

Uh, I think.  The -10 kb size, and the hover-over note saying "binary file removed", makes me think so.

**Review by inexorabletash — APPROVED** [review]

**Pull request merged**
