### PR TITLE
Hiver gov and law changes

### PR DESCRIPTION
**Pull request by mmarquee**
Further tweaks of old Hiver gov codes to T5.10 (and subsequent law changes)

### CODE REVIEW

**Comment by inexorabletash** [comment]
Let me know when this is ready to go!

**Comment by mmarquee** [comment]
This is the full run through the sectors I've previously touched/redone/generated. My only worry is paving over someone's already published work or changing a canon world - I've left Glea / Guaran / Ofilaq and Loza'tch untouched - even if there are issues. I changed Tryylin to be what the wiki says were it's Hard Times UWP, changing the 'W' to a '3' for Gov, otherwise I've left it alone. 
For K'kree worlds, I changed all the govs to valid T5.10 codes, and set the law codes as high as 1 could.

**Comment by mmarquee** [comment]
To summarize - I think I am done, pending any reviews 😃

**Comment by inexorabletash** [comment]
Awesome, thanks!

Few things for a follow-up:

* Stellar codes now require the largest star in the system to be first (that'd be sorted by class first, so Ia > Ib > II > III > IV > V > D, then temperature so O>B>A>F>G>K>M, then ratio so 0>9). That's just a warning, but there are several cases where the stars should be swapped.

* The code for Za'tachk should be Za't (you were using ZaXt)

* Did I ask for a summary of Sophont codes anywhere? I can look at adding those to the official list, at least for those which have been published. Ideally, a list of code/name/sectors.

Avereguar - 
Nonstandard sophont code: Aqar
Nonstandard sophont code: Icko
Blaskon - 
Nonstandard sophont code: Atna
Nonstandard sophont code: Drad
Nonstandard sophont code: Ldoo
Centrax - 
Nonstandard sophont code: Medr
Nonstandard sophont code: Nald
Nonstandard sophont code: Paca
Nonstandard sophont code: Ropa
Nonstandard sophont code: Weqb
Drakken - 
Nonstandard sophont code: Icaa
Nonstandard sophont code: Onkk
Nonstandard sophont code: Phle
Nonstandard sophont code: Syia
Nonstandard sophont code: Wroa
Extolian - 
Nonstandard sophont code: Albl
Nonstandard sophont code: Gask
Nonstandard sophont code: Geka
Nonstandard sophont code: Guin
Nonstandard sophont code: Pale
Nonstandard sophont code: Phli
Nonstandard sophont code: Poxi
Nonstandard sophont code: Tria
Nonstandard sophont code: Triu
Folgore - 
Nonstandard sophont code: Daga
Nonstandard sophont code: Kamu
Nonstandard sophont code: Poca
Gzirr!k'l - 
Nonstandard sophont code: ZaXt
K'trekreer - 
Nonstandard sophont code: Geen
Nonstandard sophont code: Orar
Nonstandard sophont code: Rrar
Nonstandard sophont code: Troi
Nonstandard sophont code: XXtk
Lorspane - 
Nonstandard sophont code: Ciia
Nonstandard sophont code: Luxu
Nonstandard sophont code: Sixa
Nonstandard sophont code: Spua
Nooq - 
Nonstandard sophont code: Drad
Nonstandard sophont code: Rega
Phlask - 
Nonstandard sophont code: Aoao
Nonstandard sophont code: Guua
Nonstandard sophont code: Nain
Porlock - 
Nonstandard sophont code: Anpa
Nonstandard sophont code: Atan
Nonstandard sophont code: Etga
Nonstandard sophont code: Famo
Nonstandard sophont code: Gahu
Nonstandard sophont code: Gugo
Nonstandard sophont code: Pily
Nonstandard sophont code: ZaXt
Ricenden - 
Nonstandard sophont code: Afty
Nonstandard sophont code: Ixua
Nonstandard sophont code: Kigg
Nonstandard sophont code: Thac
Nonstandard sophont code: Uapd
Nonstandard sophont code: Umva
Wrenton - 
Nonstandard sophont code: Gila
Nonstandard sophont code: Hana
Nonstandard sophont code: Kavo
Nonstandard sophont code: Kigg
Nonstandard sophont code: Kooi
Nonstandard sophont code: Lacd
Nonstandard sophont code: Nuns
Nonstandard sophont code: Ootp
Nonstandard sophont code: Wame
Nonstandard sophont code: ZaXt

**Comment by mmarquee** [comment]
I think I have sent the list in a previous merge.  
I'll change the Za'tachk code, as a separate PR.

**Comment by tjoneslo** [comment]
> The code for Za'tachk should be Za't (you were using ZaXt)

I thought the rule was for all of the non-alphabet characters in the name were to be converted to "X" (upper case X).

**Comment by inexorabletash** [comment]
That's true for sector codes. Doesn't look like that was used for sophont codes, per DonM. The list in https://travellermap.com/doc/secondsurvey#remarks comes from Marc's spreadsheet.

**Pull request merged**
