### PR TITLE
UWP fix with Jim Kundert

### PR DESCRIPTION
**Pull request by bobbyjim**
If I didn't commit these, let's do it now.

Jim Kundert talked me through some wrong assumptions Jim Fetters and I made when resolving AOTI with the Genie/Sunbane data.

The result is a relatively small changeset, but I think it's important enough to fix now.

### CODE REVIEW

**Comment by inexorabletash** [comment]
Can you make the changes to the copy in res/t5ss/data as well?

**Comment by bobbyjim** [comment]
Oh yeah that's right, that's the master.  Maybe!!  Please stand by.

**Comment by bobbyjim** [comment]
Oh it's already in there!  So I can close this one, right?

**Comment by bobbyjim** [comment]
Yeah it's in the master and that's what matters.

**Pull request closed without merging**
