### PR TITLE
Borders for the Zhodani outposts in Chtierabl & Vlanchiets Qlom

### PR DESCRIPTION
**Pull request by wvan478**
Created using the TravellerMap border maker. I've only covered the first two sectors of VQ, but the rest should be relatively simple to do because they consists of small, separated districts rather than the province of Chtierabl.

### CODE REVIEW

**Comment by wvan478** [comment]
Now I've added borders for all the other sectors in Vlanchiets Qlom as well.

**Comment by inexorabletash** [comment]
Thanks - and apologies for the delay. I went ahead and merged, although there are some glitches with the borders in Chit

Can you take a look and fix in a follow-up PR?

image


image

**Comment by wvan478** [comment]
Thanks, I'll take a look.

**Comment by wvan478** [comment]
The bottom glitch I think is occurring because of a repeated 1741: 2041 1941 1941 1841 1741 1741 1741 1641 1541 1441 1341 1241

I'm not sure what's causing the top glitch, though. Here is the relevant section of border code: 2500 2600 2700 2800 2701 2702 2802 2903 3003

**Comment by inexorabletash** [comment]
Thanks. The top one was in the adjacent sector - they need to agree on what's included or you'll get those drop-outs. I found another glitch and fixed it too.

43f53db5d315375104ac6c5e8a313279a7388e64

**Pull request merged**
