### PR TITLE
chore: added Orange to the Wilds

### PR DESCRIPTION
**Pull request by bobbyjim**

### CODE REVIEW

**Comment by inexorabletash** [comment]
merged and deployed!

**Comment by inexorabletash** [comment]
Maybe a follow-up PR to max out the borders in ZIAF?

**Comment by bobbyjim** [comment]
Heck yes, and through those parts of the Vargr Extents that I've also
worked through.

I also have my sights on Knaeleng sector, for Galaxiad reasons.

**Comment by bobbyjim** [comment]
I also want to move the state in Ilelish coreward 12 parsecs or so, so that
about half of it is in Gushemege.  My thought is that it is the survivor
element of MJD's Fourth Imperium.

**Comment by bobbyjim** [comment]
I wanted to talk that over with SOMEONE, but Jim and Matt and Thom have so
many things to talk over on
Thursday nights that I never get the chance...

**Comment by bobbyjim** [comment]
lol it would be oh so convenient for me (ha!) if I can just declare a
default background color instead of generating border data for
everything-that's-not-a-state.

But that's a first world problem.

**Pull request merged**
